// Comprehensive list of academic majors
const majorsList = [
  "Accounting",
  "Actuarial Science",
  "Aerospace Engineering",
  "African American Studies",
  "Agriculture",
  "Allied Health",
  "American Studies",
  "Animal Science",
  "Animation",
  "Anthropology",
  "Applied Linguistics",
  "Architecture",
  "Art History",
  "Artificial Intelligence",
  "Asian Studies",
  "Astronomy",
  "Astrophysics",
  "Athletic Training",
  "Atmospheric Sciences",
  "Automotive Engineering",
  "Aviation",
  "Behavioral Science",
  "Biochemistry",
  "Bioengineering",
  "Biology",
  "Biomedical Engineering",
  "Biotechnology",
  "Botany",
  "Broadcasting",
  "Business Administration",
  "Business Analytics",
  "Business Law",
  "Cell Biology",
  "Chemical Engineering",
  "Chemistry",
  "Child Development",
  "Chinese",
  "Civil Engineering",
  "Classical Studies",
  "Climate Science",
  "Cognitive Science",
  "Communications",
  "Community Health",
  "Comparative Literature",
  "Computer Engineering",
  "Computer Information Systems",
  "Computer Science",
  "Conservation Biology",
  "Construction Management",
  "Criminal Justice",
  "Culinary Arts",
  "Cybersecurity",
  "Dance",
  "Data Analytics",
  "Data Science",
  "Dental Hygiene",
  "Dentistry",
  "Digital Marketing",
  "Digital Media",
  "Earth Sciences",
  "Ecology",
  "Economics",
  "Education",
  "Educational Technology",
  "Electrical Engineering",
  "Elementary Education",
  "English Literature",
  "Entrepreneurship",
  "Environmental Design",
  "Environmental Engineering",
  "Environmental Science",
  "Environmental Studies",
  "Epidemiology",
  "Ethnic Studies",
  "European Studies",
  "Exercise Science",
  "Fashion Design",
  "Fashion Merchandising",
  "Film Studies",
  "Finance",
  "Fine Arts",
  "Food Science",
  "Forensic Science",
  "Forestry",
  "French",
  "Game Design",
  "Gender Studies",
  "General Business",
  "Genetics",
  "Geography",
  "Geology",
  "German",
  "Gerontology",
  "Graphic Design",
  "Health Administration",
  "Health Informatics",
  "Health Sciences",
  "Healthcare Management",
  "History",
  "Horticulture",
  "Hospitality Management",
  "Human Development",
  "Human Resources",
  "Human-Computer Interaction",
  "Humanities",
  "Illustration",
  "Industrial Design",
  "Industrial Engineering",
  "Information Science",
  "Information Systems",
  "Information Technology",
  "Interior Design",
  "International Business",
  "International Relations",
  "Italian",
  "Japanese",
  "Journalism",
  "Kinesiology",
  "Landscape Architecture",
  "Latin American Studies",
  "Legal Studies",
  "Liberal Arts",
  "Library Science",
  "Linguistics",
  "Logistics",
  "Management Information Systems",
  "Marine Biology",
  "Marketing",
  "Materials Science",
  "Mathematics",
  "Mechanical Engineering",
  "Media Studies",
  "Medical Technology",
  "Meteorology",
  "Microbiology",
  "Middle Eastern Studies",
  "Military Science",
  "Music",
  "Music Education",
  "Music Production",
  "Nanoscience",
  "Natural Resources",
  "Neuroscience",
  "Nuclear Engineering",
  "Nursing",
  "Nutrition",
  "Occupational Therapy",
  "Oceanography",
  "Operations & Business Analytics",
  "Optometry",
  "Organizational Leadership",
  "Paleontology",
  "Paralegal Studies",
  "Petroleum Engineering",
  "Pharmacology",
  "Pharmacy",
  "Philosophy",
  "Photography",
  "Physical Education",
  "Physical Therapy",
  "Physician Assistant Studies",
  "Physics",
  "Plant Science",
  "Political Science",
  "Pre-Business Administration",
  "Pre-Dental",
  "Pre-Law",
  "Pre-Medicine",
  "Pre-Pharmacy",
  "Pre-Veterinary Medicine",
  "Product Design",
  "Project Management",
  "Psychology",
  "Public Administration",
  "Public Health",
  "Public Policy",
  "Public Relations",
  "Radiologic Technology",
  "Real Estate",
  "Recreation Management",
  "Religious Studies",
  "Renewable Energy",
  "Respiratory Therapy",
  "Robotics",
  "Russian",
  "Science Education",
  "Secondary Education",
  "Social Work",
  "Sociology",
  "Software Engineering",
  "Soil Science",
  "Spanish",
  "Special Education",
  "Speech Pathology",
  "Sports Management",
  "Statistics",
  "Supply Chain Management",
  "Sustainable Development",
  "Systems Engineering",
  "Taxation",
  "Teacher Education",
  "Technical Writing",
  "Theater",
  "Theology",
  "Tourism Management",
  "Toxicology",
  "Translation Studies",
  "Transportation Engineering",
  "Urban Planning",
  "User Experience Design",
  "Veterinary Science",
  "Visual Arts",
  "Web Design",
  "Web Development",
  "Wildlife Biology",
  "Women's Studies",
  "Zoology",
];

export default majorsList; 